name: Bug 报告
description: 在提出问题前请先自行排除服务器端问题和升级到最新客户端，同时也请通过搜索确认是否有人提出过相同问题。
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## 在反馈问题前请务必确认：
        1. **已自行排除服务器端问题。**
        2. **已升级到最新客户端版本。**
        3. **已通过搜索确认是否有人提出过相同问题。**
        4. **已确认自己的电脑系统环境是受支持的。**
  - type: input
    id: "os-version"
    attributes:
      label: "操作系统和版本"
      description: "操作系统和版本"
    validations:
      required: true
  - type: input
    id: "expectation"
    attributes:
      label: "预期情况"
      description: "描述你认为应该发生什么"
    validations:
      required: true
  - type: textarea
    id: "describe-the-bug"
    attributes:
      label: "实际情况"
      description: "描述实际发生了什么"
    validations:
      required: true
  - type: textarea
    id: "reproduction-method"
    attributes:
      label: "复现方法"
      description: "在BUG出现前执行了哪些操作"
      placeholder: 标序号
    validations:
      required: true
  - type: textarea
    id: "log"
    attributes:
      label: "日志信息"
      description: "位置在软件当前目录下的guiLogs"
      placeholder: 在日志开始和结束位置粘贴冒号后的内容：```
    validations:
      required: true
  - type: textarea
    id: "more"
    attributes:
      label: "额外信息"
      description: "可选"
    validations:
      required: false
  - type: checkboxes
    id: "latest-version"
    attributes:
      label: "我确认已更新至最新版本"
      description: "否则请更新后尝试"
      options:
        - label: 是
          required: true
  - type: checkboxes
    id: "issues"
    attributes:
      label: "我确认已查询历史issues"
      description: "否则请查询后提出"
      options:
        - label: 是
          required: true
  - type: checkboxes
    id: "system-version"
    attributes:
      label: "我确认系统版本是受支持的"
      description: "否则请切换后尝试"
      options:
        - label: 是
          required: true
