//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace v2rayN.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("v2rayN.Resx.ResUI", typeof(ResUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to append rules? Choose yes to append, choose otherwise to replace.
        /// </summary>
        internal static string AddBatchRoutingRulesYesNo {
            get {
                return ResourceManager.GetString("AddBatchRoutingRulesYesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All servers.
        /// </summary>
        internal static string AllGroupServers {
            get {
                return ResourceManager.GetString("AllGroupServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch export subscription to clipboard successfully.
        /// </summary>
        internal static string BatchExportSubscriptionSuccessfully {
            get {
                return ResourceManager.GetString("BatchExportSubscriptionSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch export share URL to clipboard successfully.
        /// </summary>
        internal static string BatchExportURLSuccessfully {
            get {
                return ResourceManager.GetString("BatchExportURLSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the server settings first.
        /// </summary>
        internal static string CheckServerSettings {
            get {
                return ResourceManager.GetString("CheckServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration format.
        /// </summary>
        internal static string ConfigurationFormatIncorrect {
            get {
                return ResourceManager.GetString("ConfigurationFormatIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note that custom configuration relies entirely on your own configuration and does not work with all settings. If you want to use the system proxy, please modify the listening port manually..
        /// </summary>
        internal static string CustomServerTips {
            get {
                return ResourceManager.GetString("CustomServerTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string downloadSpeed {
            get {
                return ResourceManager.GetString("downloadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to download? {0}.
        /// </summary>
        internal static string DownloadYesNo {
            get {
                return ResourceManager.GetString("DownloadYesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert configuration file.
        /// </summary>
        internal static string FailedConversionConfiguration {
            get {
                return ResourceManager.GetString("FailedConversionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate default configuration file.
        /// </summary>
        internal static string FailedGenDefaultConfiguration {
            get {
                return ResourceManager.GetString("FailedGenDefaultConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Failed to get the default configuration.
        /// </summary>
        internal static string FailedGetDefaultConfiguration {
            get {
                return ResourceManager.GetString("FailedGetDefaultConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import custom configuration server.
        /// </summary>
        internal static string FailedImportedCustomServer {
            get {
                return ResourceManager.GetString("FailedImportedCustomServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read configuration file.
        /// </summary>
        internal static string FailedReadConfiguration {
            get {
                return ResourceManager.GetString("FailedReadConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the correct custom DNS.
        /// </summary>
        internal static string FillCorrectDNSText {
            get {
                return ResourceManager.GetString("FillCorrectDNSText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the correct format server port.
        /// </summary>
        internal static string FillCorrectServerPort {
            get {
                return ResourceManager.GetString("FillCorrectServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the KCP parameters correctly.
        /// </summary>
        internal static string FillKcpParameters {
            get {
                return ResourceManager.GetString("FillKcpParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the local listening port.
        /// </summary>
        internal static string FillLocalListeningPort {
            get {
                return ResourceManager.GetString("FillLocalListeningPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the password.
        /// </summary>
        internal static string FillPassword {
            get {
                return ResourceManager.GetString("FillPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the server address.
        /// </summary>
        internal static string FillServerAddress {
            get {
                return ResourceManager.GetString("FillServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please browse to import server configuration.
        /// </summary>
        internal static string FillServerAddressCustom {
            get {
                return ResourceManager.GetString("FillServerAddressCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the user ID.
        /// </summary>
        internal static string FillUUID {
            get {
                return ResourceManager.GetString("FillUUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is not the correct client configuration file, please check.
        /// </summary>
        internal static string IncorrectClientConfiguration {
            get {
                return ResourceManager.GetString("IncorrectClientConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is not the correct configuration, please check.
        /// </summary>
        internal static string Incorrectconfiguration {
            get {
                return ResourceManager.GetString("Incorrectconfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is not the correct server configuration file, please check.
        /// </summary>
        internal static string IncorrectServerConfiguration {
            get {
                return ResourceManager.GetString("IncorrectServerConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Configuration.
        /// </summary>
        internal static string InitialConfiguration {
            get {
                return ResourceManager.GetString("InitialConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already up to date..
        /// </summary>
        internal static string IsLatestCore {
            get {
                return ResourceManager.GetString("IsLatestCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already up to date..
        /// </summary>
        internal static string IsLatestN {
            get {
                return ResourceManager.GetString("IsLatestN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAN.
        /// </summary>
        internal static string LabLAN {
            get {
                return ResourceManager.GetString("LabLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string LabLocal {
            get {
                return ResourceManager.GetString("LabLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string LvAddress {
            get {
                return ResourceManager.GetString("LvAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        internal static string LvAlias {
            get {
                return ResourceManager.GetString("LvAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string LvCount {
            get {
                return ResourceManager.GetString("LvCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Icon.
        /// </summary>
        internal static string LvCustomIcon {
            get {
                return ResourceManager.GetString("LvCustomIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string LvEncryptionMethod {
            get {
                return ResourceManager.GetString("LvEncryptionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string LvPort {
            get {
                return ResourceManager.GetString("LvPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remarks.
        /// </summary>
        internal static string LvRemarks {
            get {
                return ResourceManager.GetString("LvRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string LvServiceType {
            get {
                return ResourceManager.GetString("LvServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subs.
        /// </summary>
        internal static string LvSubscription {
            get {
                return ResourceManager.GetString("LvSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Results.
        /// </summary>
        internal static string LvTestResults {
            get {
                return ResourceManager.GetString("LvTestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TLS.
        /// </summary>
        internal static string LvTLS {
            get {
                return ResourceManager.GetString("LvTLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download traffic today.
        /// </summary>
        internal static string LvTodayDownloadDataAmount {
            get {
                return ResourceManager.GetString("LvTodayDownloadDataAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload traffic today.
        /// </summary>
        internal static string LvTodayUploadDataAmount {
            get {
                return ResourceManager.GetString("LvTodayUploadDataAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total download traffic.
        /// </summary>
        internal static string LvTotalDownloadDataAmount {
            get {
                return ResourceManager.GetString("LvTotalDownloadDataAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total upload traffic.
        /// </summary>
        internal static string LvTotalUploadDataAmount {
            get {
                return ResourceManager.GetString("LvTotalUploadDataAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport.
        /// </summary>
        internal static string LvTransportProtocol {
            get {
                return ResourceManager.GetString("LvTransportProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string LvUrl {
            get {
                return ResourceManager.GetString("LvUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string MediumFresh {
            get {
                return ResourceManager.GetString("MediumFresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear original subscription content.
        /// </summary>
        internal static string MsgClearSubscription {
            get {
                return ResourceManager.GetString("MsgClearSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download GeoFile: {0} successfully.
        /// </summary>
        internal static string MsgDownloadGeoFileSuccessfully {
            get {
                return ResourceManager.GetString("MsgDownloadGeoFileSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Core successfully.
        /// </summary>
        internal static string MsgDownloadV2rayCoreSuccessfully {
            get {
                return ResourceManager.GetString("MsgDownloadV2rayCoreSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import subscription content.
        /// </summary>
        internal static string MsgFailedImportSubscription {
            get {
                return ResourceManager.GetString("MsgFailedImportSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get subscription content successfully.
        /// </summary>
        internal static string MsgGetSubscriptionSuccessfully {
            get {
                return ResourceManager.GetString("MsgGetSubscriptionSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information (Filter : {0}).
        /// </summary>
        internal static string MsgInformationTitle {
            get {
                return ResourceManager.GetString("MsgInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the address (Url).
        /// </summary>
        internal static string MsgNeedUrl {
            get {
                return ResourceManager.GetString("MsgNeedUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid subscriptions set.
        /// </summary>
        internal static string MsgNoValidSubscription {
            get {
                return ResourceManager.GetString("MsgNoValidSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAC update failed.
        /// </summary>
        internal static string MsgPACUpdateFailed {
            get {
                return ResourceManager.GetString("MsgPACUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAC update succeeded.
        /// </summary>
        internal static string MsgPACUpdateSuccessfully {
            get {
                return ResourceManager.GetString("MsgPACUpdateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve {0} successfully.
        /// </summary>
        internal static string MsgParsingSuccessfully {
            get {
                return ResourceManager.GetString("MsgParsingSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers (Filter : {0}).
        /// </summary>
        internal static string MsgServerTitle {
            get {
                return ResourceManager.GetString("MsgServerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplify PAC Success.
        /// </summary>
        internal static string MsgSimplifyPAC {
            get {
                return ResourceManager.GetString("MsgSimplifyPAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start getting subscriptions.
        /// </summary>
        internal static string MsgStartGettingSubscriptions {
            get {
                return ResourceManager.GetString("MsgStartGettingSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start updating {0}....
        /// </summary>
        internal static string MsgStartUpdating {
            get {
                return ResourceManager.GetString("MsgStartUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start updating PAC....
        /// </summary>
        internal static string MsgStartUpdatingPAC {
            get {
                return ResourceManager.GetString("MsgStartUpdatingPAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid subscription content.
        /// </summary>
        internal static string MsgSubscriptionDecodingFailed {
            get {
                return ResourceManager.GetString("MsgSubscriptionDecodingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is unpacking....
        /// </summary>
        internal static string MsgUnpacking {
            get {
                return ResourceManager.GetString("MsgUnpacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update subscription end.
        /// </summary>
        internal static string MsgUpdateSubscriptionEnd {
            get {
                return ResourceManager.GetString("MsgUpdateSubscriptionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update subscription starts.
        /// </summary>
        internal static string MsgUpdateSubscriptionStart {
            get {
                return ResourceManager.GetString("MsgUpdateSubscriptionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Core successfully.
        /// </summary>
        internal static string MsgUpdateV2rayCoreSuccessfully {
            get {
                return ResourceManager.GetString("MsgUpdateV2rayCoreSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Core successfully! Restarting service....
        /// </summary>
        internal static string MsgUpdateV2rayCoreSuccessfullyMore {
            get {
                return ResourceManager.GetString("MsgUpdateV2rayCoreSuccessfullyMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  This feature relies on the Http global proxy, please set it correctly first..
        /// </summary>
        internal static string NeedHttpGlobalProxy {
            get {
                return ResourceManager.GetString("NeedHttpGlobalProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-vmess or ss protocol.
        /// </summary>
        internal static string NonvmessOrssProtocol {
            get {
                return ResourceManager.GetString("NonvmessOrssProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  non-Vmess service, this feature is invalid.
        /// </summary>
        internal static string NonVmessService {
            get {
                return ResourceManager.GetString("NonVmessService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core not found, please download: {0}.
        /// </summary>
        internal static string NotFoundCore {
            get {
                return ResourceManager.GetString("NotFoundCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan completed, no valid QR code found.
        /// </summary>
        internal static string NoValidQRcodeFound {
            get {
                return ResourceManager.GetString("NoValidQRcodeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  operation failed, please check and retry.
        /// </summary>
        internal static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation success.
        /// </summary>
        internal static string OperationSuccess {
            get {
                return ResourceManager.GetString("OperationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Fill Remarks.
        /// </summary>
        internal static string PleaseFillRemarks {
            get {
                return ResourceManager.GetString("PleaseFillRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the encryption method.
        /// </summary>
        internal static string PleaseSelectEncryption {
            get {
                return ResourceManager.GetString("PleaseSelectEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a protocol.
        /// </summary>
        internal static string PleaseSelectProtocol {
            get {
                return ResourceManager.GetString("PleaseSelectProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select rules.
        /// </summary>
        internal static string PleaseSelectRules {
            get {
                return ResourceManager.GetString("PleaseSelectRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the server first.
        /// </summary>
        internal static string PleaseSelectServer {
            get {
                return ResourceManager.GetString("PleaseSelectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        internal static string QuickFresh {
            get {
                return ResourceManager.GetString("QuickFresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global hotkey {0} registered failed, reason {1}.
        /// </summary>
        internal static string RegisterGlobalHotkeyFailed {
            get {
                return ResourceManager.GetString("RegisterGlobalHotkeyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global hotkey {0} registered successfully.
        /// </summary>
        internal static string RegisterGlobalHotkeySuccessfully {
            get {
                return ResourceManager.GetString("RegisterGlobalHotkeySuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers deduplication completed. Old: {0}, New: {1}..
        /// </summary>
        internal static string RemoveDuplicateServerResult {
            get {
                return ResourceManager.GetString("RemoveDuplicateServerResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove the rules?.
        /// </summary>
        internal static string RemoveRules {
            get {
                return ResourceManager.GetString("RemoveRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove the server?.
        /// </summary>
        internal static string RemoveServer {
            get {
                return ResourceManager.GetString("RemoveServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0},One of the required..
        /// </summary>
        internal static string RoutingRuleDetailRequiredTips {
            get {
                return ResourceManager.GetString("RoutingRuleDetailRequiredTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client configuration file is saved at: {0}.
        /// </summary>
        internal static string SaveClientConfigurationIn {
            get {
                return ResourceManager.GetString("SaveClientConfigurationIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server configuration file is saved at: {0}.
        /// </summary>
        internal static string SaveServerConfigurationIn {
            get {
                return ResourceManager.GetString("SaveServerConfigurationIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        internal static string SlowFresh {
            get {
                return ResourceManager.GetString("SlowFresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: This feature relies on the Http global proxy. Please manually adjust the Http global proxy and active node after testing..
        /// </summary>
        internal static string SpeedServerTips {
            get {
                return ResourceManager.GetString("SpeedServerTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Test....
        /// </summary>
        internal static string Speedtesting {
            get {
                return ResourceManager.GetString("Speedtesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAC failed to start. Please run this program as Administrator..
        /// </summary>
        internal static string StartPacFailed {
            get {
                return ResourceManager.GetString("StartPacFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start service ({0})....
        /// </summary>
        internal static string StartService {
            get {
                return ResourceManager.GetString("StartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration successful
        ///{0}.
        /// </summary>
        internal static string SuccessfulConfiguration {
            get {
                return ResourceManager.GetString("SuccessfulConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom configuration server imported successfully..
        /// </summary>
        internal static string SuccessfullyImportedCustomServer {
            get {
                return ResourceManager.GetString("SuccessfullyImportedCustomServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} servers have been imported from clipboard..
        /// </summary>
        internal static string SuccessfullyImportedServerViaClipboard {
            get {
                return ResourceManager.GetString("SuccessfullyImportedServerViaClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan import URL successfully.
        /// </summary>
        internal static string SuccessfullyImportedServerViaScan {
            get {
                return ResourceManager.GetString("SuccessfullyImportedServerViaScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System proxy.
        /// </summary>
        internal static string SystemProxy {
            get {
                return ResourceManager.GetString("SystemProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ping of current service: {0} ms.
        /// </summary>
        internal static string TestMeOutput {
            get {
                return ResourceManager.GetString("TestMeOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many servers, please open the main interface.
        /// </summary>
        internal static string TooManyServersTip {
            get {
                return ResourceManager.GetString("TooManyServersTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *tcp camouflage type.
        /// </summary>
        internal static string TransportHeaderTypeTip1 {
            get {
                return ResourceManager.GetString("TransportHeaderTypeTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *kcp camouflage type.
        /// </summary>
        internal static string TransportHeaderTypeTip2 {
            get {
                return ResourceManager.GetString("TransportHeaderTypeTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *QUIC camouflage type.
        /// </summary>
        internal static string TransportHeaderTypeTip3 {
            get {
                return ResourceManager.GetString("TransportHeaderTypeTip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *grpc mode.
        /// </summary>
        internal static string TransportHeaderTypeTip4 {
            get {
                return ResourceManager.GetString("TransportHeaderTypeTip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *ws path.
        /// </summary>
        internal static string TransportPathTip1 {
            get {
                return ResourceManager.GetString("TransportPathTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *h2 path.
        /// </summary>
        internal static string TransportPathTip2 {
            get {
                return ResourceManager.GetString("TransportPathTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *QUIC key/Kcp seed.
        /// </summary>
        internal static string TransportPathTip3 {
            get {
                return ResourceManager.GetString("TransportPathTip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *grpc serviceName.
        /// </summary>
        internal static string TransportPathTip4 {
            get {
                return ResourceManager.GetString("TransportPathTip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Kcp seed.
        /// </summary>
        internal static string TransportPathTip5 {
            get {
                return ResourceManager.GetString("TransportPathTip5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *http host Separated by commas (,).
        /// </summary>
        internal static string TransportRequestHostTip1 {
            get {
                return ResourceManager.GetString("TransportRequestHostTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *ws host.
        /// </summary>
        internal static string TransportRequestHostTip2 {
            get {
                return ResourceManager.GetString("TransportRequestHostTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *h2 host Separated by commas (,).
        /// </summary>
        internal static string TransportRequestHostTip3 {
            get {
                return ResourceManager.GetString("TransportRequestHostTip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *QUIC securty.
        /// </summary>
        internal static string TransportRequestHostTip4 {
            get {
                return ResourceManager.GetString("TransportRequestHostTip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungrouped.
        /// </summary>
        internal static string UngroupedServers {
            get {
                return ResourceManager.GetString("UngroupedServers", resourceCulture);
            }
        }
    }
}
