//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace v2rayN.Resx {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResUI() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("v2rayN.Resx.ResUI", typeof(ResUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Batch export subscription to clipboard successfully 的本地化字符串。
        /// </summary>
        internal static string BatchExportSubscriptionSuccessfully {
            get {
                return ResourceManager.GetString("BatchExportSubscriptionSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch export share URL to clipboard successfully 的本地化字符串。
        /// </summary>
        internal static string BatchExportURLSuccessfully {
            get {
                return ResourceManager.GetString("BatchExportURLSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please check the server settings first 的本地化字符串。
        /// </summary>
        internal static string CheckServerSettings {
            get {
                return ResourceManager.GetString("CheckServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  configuration format is incorrect 的本地化字符串。
        /// </summary>
        internal static string ConfigurationFormatIncorrect {
            get {
                return ResourceManager.GetString("ConfigurationFormatIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note that custom configuration relies entirely on your own configuration and does not work with all settings. The system agent is available when the socks port is equal to the port in the settings in the custom configuration inbound. 的本地化字符串。
        /// </summary>
        internal static string CustomServerTips {
            get {
                return ResourceManager.GetString("CustomServerTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading... 的本地化字符串。
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DOWN 的本地化字符串。
        /// </summary>
        internal static string downloadSpeed {
            get {
                return ResourceManager.GetString("downloadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whether to download? {0} 的本地化字符串。
        /// </summary>
        internal static string DownloadYesNo {
            get {
                return ResourceManager.GetString("DownloadYesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to convert configuration file 的本地化字符串。
        /// </summary>
        internal static string FailedConversionConfiguration {
            get {
                return ResourceManager.GetString("FailedConversionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to generate default configuration file 的本地化字符串。
        /// </summary>
        internal static string FailedGenDefaultConfiguration {
            get {
                return ResourceManager.GetString("FailedGenDefaultConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Failed to get the default configuration 的本地化字符串。
        /// </summary>
        internal static string FailedGetDefaultConfiguration {
            get {
                return ResourceManager.GetString("FailedGetDefaultConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to import custom configuration server 的本地化字符串。
        /// </summary>
        internal static string FailedImportedCustomServer {
            get {
                return ResourceManager.GetString("FailedImportedCustomServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to read configuration file 的本地化字符串。
        /// </summary>
        internal static string FailedReadConfiguration {
            get {
                return ResourceManager.GetString("FailedReadConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please fill in the correct format extra ID 的本地化字符串。
        /// </summary>
        internal static string FillCorrectAlterId {
            get {
                return ResourceManager.GetString("FillCorrectAlterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please fill in the correct format server port 的本地化字符串。
        /// </summary>
        internal static string FillCorrectServerPort {
            get {
                return ResourceManager.GetString("FillCorrectServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please fill in the KCP parameters correctly 的本地化字符串。
        /// </summary>
        internal static string FillKcpParameters {
            get {
                return ResourceManager.GetString("FillKcpParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please fill in the local listening port 的本地化字符串。
        /// </summary>
        internal static string FillLocalListeningPort {
            get {
                return ResourceManager.GetString("FillLocalListeningPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please fill in the password 的本地化字符串。
        /// </summary>
        internal static string FillPassword {
            get {
                return ResourceManager.GetString("FillPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please fill in the server address 的本地化字符串。
        /// </summary>
        internal static string FillServerAddress {
            get {
                return ResourceManager.GetString("FillServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please fill in the user ID 的本地化字符串。
        /// </summary>
        internal static string FillUUID {
            get {
                return ResourceManager.GetString("FillUUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  is not the correct client configuration file, please check 的本地化字符串。
        /// </summary>
        internal static string IncorrectClientConfiguration {
            get {
                return ResourceManager.GetString("IncorrectClientConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  is not the correct configuration, please check 的本地化字符串。
        /// </summary>
        internal static string Incorrectconfiguration {
            get {
                return ResourceManager.GetString("Incorrectconfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  is not the correct server configuration file, please check 的本地化字符串。
        /// </summary>
        internal static string IncorrectServerConfiguration {
            get {
                return ResourceManager.GetString("IncorrectServerConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initial Configuration 的本地化字符串。
        /// </summary>
        internal static string InitialConfiguration {
            get {
                return ResourceManager.GetString("InitialConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} already up to date. 的本地化字符串。
        /// </summary>
        internal static string IsLatestCore {
            get {
                return ResourceManager.GetString("IsLatestCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} already up to date. 的本地化字符串。
        /// </summary>
        internal static string IsLatestN {
            get {
                return ResourceManager.GetString("IsLatestN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        internal static string LvAddress {
            get {
                return ResourceManager.GetString("LvAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alias 的本地化字符串。
        /// </summary>
        internal static string LvAlias {
            get {
                return ResourceManager.GetString("LvAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Security 的本地化字符串。
        /// </summary>
        internal static string LvEncryptionMethod {
            get {
                return ResourceManager.GetString("LvEncryptionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        internal static string LvPort {
            get {
                return ResourceManager.GetString("LvPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string LvServiceType {
            get {
                return ResourceManager.GetString("LvServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subs 的本地化字符串。
        /// </summary>
        internal static string LvSubscription {
            get {
                return ResourceManager.GetString("LvSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Results 的本地化字符串。
        /// </summary>
        internal static string LvTestResults {
            get {
                return ResourceManager.GetString("LvTestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Today download traffic 的本地化字符串。
        /// </summary>
        internal static string LvTodayDownloadDataAmount {
            get {
                return ResourceManager.GetString("LvTodayDownloadDataAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Today upload traffic 的本地化字符串。
        /// </summary>
        internal static string LvTodayUploadDataAmount {
            get {
                return ResourceManager.GetString("LvTodayUploadDataAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total download traffic 的本地化字符串。
        /// </summary>
        internal static string LvTotalDownloadDataAmount {
            get {
                return ResourceManager.GetString("LvTotalDownloadDataAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total upload traffic 的本地化字符串。
        /// </summary>
        internal static string LvTotalUploadDataAmount {
            get {
                return ResourceManager.GetString("LvTotalUploadDataAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transport 的本地化字符串。
        /// </summary>
        internal static string LvTransportProtocol {
            get {
                return ResourceManager.GetString("LvTransportProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MediumFresh 的本地化字符串。
        /// </summary>
        internal static string MediumFresh {
            get {
                return ResourceManager.GetString("MediumFresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear original subscription content 的本地化字符串。
        /// </summary>
        internal static string MsgClearSubscription {
            get {
                return ResourceManager.GetString("MsgClearSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download V2ray successfully 的本地化字符串。
        /// </summary>
        internal static string MsgDownloadV2rayCoreSuccessfully {
            get {
                return ResourceManager.GetString("MsgDownloadV2rayCoreSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to import subscription content 的本地化字符串。
        /// </summary>
        internal static string MsgFailedImportSubscription {
            get {
                return ResourceManager.GetString("MsgFailedImportSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get the subscription content successfully 的本地化字符串。
        /// </summary>
        internal static string MsgGetSubscriptionSuccessfully {
            get {
                return ResourceManager.GetString("MsgGetSubscriptionSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No valid subscriptions set 的本地化字符串。
        /// </summary>
        internal static string MsgNoValidSubscription {
            get {
                return ResourceManager.GetString("MsgNoValidSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PAC update failed 的本地化字符串。
        /// </summary>
        internal static string MsgPACUpdateFailed {
            get {
                return ResourceManager.GetString("MsgPACUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PAC update succeeded 的本地化字符串。
        /// </summary>
        internal static string MsgPACUpdateSuccessfully {
            get {
                return ResourceManager.GetString("MsgPACUpdateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resolve {0} successfully 的本地化字符串。
        /// </summary>
        internal static string MsgParsingSuccessfully {
            get {
                return ResourceManager.GetString("MsgParsingSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simplify PAC Success 的本地化字符串。
        /// </summary>
        internal static string MsgSimplifyPAC {
            get {
                return ResourceManager.GetString("MsgSimplifyPAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start getting subscriptions 的本地化字符串。
        /// </summary>
        internal static string MsgStartGettingSubscriptions {
            get {
                return ResourceManager.GetString("MsgStartGettingSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start updating {0}... 的本地化字符串。
        /// </summary>
        internal static string MsgStartUpdating {
            get {
                return ResourceManager.GetString("MsgStartUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start updating PAC... 的本地化字符串。
        /// </summary>
        internal static string MsgStartUpdatingPAC {
            get {
                return ResourceManager.GetString("MsgStartUpdatingPAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subscription content decoding failed (non-BASE64 code) 的本地化字符串。
        /// </summary>
        internal static string MsgSubscriptionDecodingFailed {
            get {
                return ResourceManager.GetString("MsgSubscriptionDecodingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is unpacking... 的本地化字符串。
        /// </summary>
        internal static string MsgUnpacking {
            get {
                return ResourceManager.GetString("MsgUnpacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update subscription end 的本地化字符串。
        /// </summary>
        internal static string MsgUpdateSubscriptionEnd {
            get {
                return ResourceManager.GetString("MsgUpdateSubscriptionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update subscription starts 的本地化字符串。
        /// </summary>
        internal static string MsgUpdateSubscriptionStart {
            get {
                return ResourceManager.GetString("MsgUpdateSubscriptionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update V2rayCore successfully 的本地化字符串。
        /// </summary>
        internal static string MsgUpdateV2rayCoreSuccessfully {
            get {
                return ResourceManager.GetString("MsgUpdateV2rayCoreSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update V2rayCore successfully! Restarting service... 的本地化字符串。
        /// </summary>
        internal static string MsgUpdateV2rayCoreSuccessfullyMore {
            get {
                return ResourceManager.GetString("MsgUpdateV2rayCoreSuccessfullyMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  This feature relies on the Http global proxy, please set it correctly first. 的本地化字符串。
        /// </summary>
        internal static string NeedHttpGlobalProxy {
            get {
                return ResourceManager.GetString("NeedHttpGlobalProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Non-vmess or ss protocol 的本地化字符串。
        /// </summary>
        internal static string NonvmessOrssProtocol {
            get {
                return ResourceManager.GetString("NonvmessOrssProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  non-Vmess service, this feature is invalid 的本地化字符串。
        /// </summary>
        internal static string NonVmessService {
            get {
                return ResourceManager.GetString("NonVmessService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V2ray-core not found, please download: {0} 的本地化字符串。
        /// </summary>
        internal static string NotFoundCore {
            get {
                return ResourceManager.GetString("NotFoundCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan completed, no valid QR code found 的本地化字符串。
        /// </summary>
        internal static string NoValidQRcodeFound {
            get {
                return ResourceManager.GetString("NoValidQRcodeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  operation failed, please check retry 的本地化字符串。
        /// </summary>
        internal static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Fill Remarks 的本地化字符串。
        /// </summary>
        internal static string PleaseFillRemarks {
            get {
                return ResourceManager.GetString("PleaseFillRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the encryption method 的本地化字符串。
        /// </summary>
        internal static string PleaseSelectEncryption {
            get {
                return ResourceManager.GetString("PleaseSelectEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select an agreement 的本地化字符串。
        /// </summary>
        internal static string PleaseSelectProtocol {
            get {
                return ResourceManager.GetString("PleaseSelectProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the server first 的本地化字符串。
        /// </summary>
        internal static string PleaseSelectServer {
            get {
                return ResourceManager.GetString("PleaseSelectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QuickFresh 的本地化字符串。
        /// </summary>
        internal static string QuickFresh {
            get {
                return ResourceManager.GetString("QuickFresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Servers deduplication completed. Old: {0}, New: {1}. 的本地化字符串。
        /// </summary>
        internal static string RemoveDuplicateServerResult {
            get {
                return ResourceManager.GetString("RemoveDuplicateServerResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to remove the server? 的本地化字符串。
        /// </summary>
        internal static string RemoveServer {
            get {
                return ResourceManager.GetString("RemoveServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bypass CN 的本地化字符串。
        /// </summary>
        internal static string RoutingModeBypassCN {
            get {
                return ResourceManager.GetString("RoutingModeBypassCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bypass LAN 的本地化字符串。
        /// </summary>
        internal static string RoutingModeBypassLAN {
            get {
                return ResourceManager.GetString("RoutingModeBypassLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bypass LAN+CN 的本地化字符串。
        /// </summary>
        internal static string RoutingModeBypassLANCN {
            get {
                return ResourceManager.GetString("RoutingModeBypassLANCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global 的本地化字符串。
        /// </summary>
        internal static string RoutingModeGlobal {
            get {
                return ResourceManager.GetString("RoutingModeGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The client configuration file is saved at: {0} 的本地化字符串。
        /// </summary>
        internal static string SaveClientConfigurationIn {
            get {
                return ResourceManager.GetString("SaveClientConfigurationIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The server configuration file is saved at: {0} 的本地化字符串。
        /// </summary>
        internal static string SaveServerConfigurationIn {
            get {
                return ResourceManager.GetString("SaveServerConfigurationIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ... 的本地化字符串。
        /// </summary>
        internal static string ServerLatencyChecking {
            get {
                return ResourceManager.GetString("ServerLatencyChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SlowFresh 的本地化字符串。
        /// </summary>
        internal static string SlowFresh {
            get {
                return ResourceManager.GetString("SlowFresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note: After this function relies on the Http global proxy test, please manually adjust the Http global proxy and active node! 的本地化字符串。
        /// </summary>
        internal static string SpeedServerTips {
            get {
                return ResourceManager.GetString("SpeedServerTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PAC failed to start. Run it with Admin right. 的本地化字符串。
        /// </summary>
        internal static string StartPacFailed {
            get {
                return ResourceManager.GetString("StartPacFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start service ({0})... 的本地化字符串。
        /// </summary>
        internal static string StartService {
            get {
                return ResourceManager.GetString("StartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successful configuration
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string SuccessfulConfiguration {
            get {
                return ResourceManager.GetString("SuccessfulConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully imported custom configuration server 的本地化字符串。
        /// </summary>
        internal static string SuccessfullyImportedCustomServer {
            get {
                return ResourceManager.GetString("SuccessfullyImportedCustomServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} servers have been imported from clipboard. 的本地化字符串。
        /// </summary>
        internal static string SuccessfullyImportedServerViaClipboard {
            get {
                return ResourceManager.GetString("SuccessfullyImportedServerViaClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan import URL successfully 的本地化字符串。
        /// </summary>
        internal static string SuccessfullyImportedServerViaScan {
            get {
                return ResourceManager.GetString("SuccessfullyImportedServerViaScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The ping of current service: {0} 的本地化字符串。
        /// </summary>
        internal static string TestMeOutput {
            get {
                return ResourceManager.GetString("TestMeOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latency: {0} 的本地化字符串。
        /// </summary>
        internal static string toolSslServerLatency {
            get {
                return ResourceManager.GetString("toolSslServerLatency", resourceCulture);
            }
        }
    }
}
