//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazTool.Resx {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AmazTool.Resx.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to terminate the v2rayN.Close it manually,or the upgrade may fail. 的本地化字符串。
        /// </summary>
        internal static string FailedTerminateProcess {
            get {
                return ResourceManager.GetString("FailedTerminateProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to extract the update package. 的本地化字符串。
        /// </summary>
        internal static string FailedUnzipping {
            get {
                return ResourceManager.GetString("FailedUnzipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upgrade failed. 的本地化字符串。
        /// </summary>
        internal static string FailedUpgrade {
            get {
                return ResourceManager.GetString("FailedUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please run it from the main application. 的本地化字符串。
        /// </summary>
        internal static string Guidelines {
            get {
                return ResourceManager.GetString("Guidelines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information 的本地化字符串。
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In progress, please wait... 的本地化字符串。
        /// </summary>
        internal static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start v2rayN, please wait... 的本地化字符串。
        /// </summary>
        internal static string Restartv2rayN {
            get {
                return ResourceManager.GetString("Restartv2rayN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start extracting the update package... 的本地化字符串。
        /// </summary>
        internal static string StartUnzipping {
            get {
                return ResourceManager.GetString("StartUnzipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully extracted the update package. 的本地化字符串。
        /// </summary>
        internal static string SuccessUnzipping {
            get {
                return ResourceManager.GetString("SuccessUnzipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upgrade success. 的本地化字符串。
        /// </summary>
        internal static string SuccessUpgrade {
            get {
                return ResourceManager.GetString("SuccessUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try to terminate the v2rayN process... 的本地化字符串。
        /// </summary>
        internal static string TryTerminateProcess {
            get {
                return ResourceManager.GetString("TryTerminateProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upgrade failed, file not found. 的本地化字符串。
        /// </summary>
        internal static string UpgradeFileNotFound {
            get {
                return ResourceManager.GetString("UpgradeFileNotFound", resourceCulture);
            }
        }
    }
}
