<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="TUnit.Assertions.Should" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\v2rayN.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="TUnit" />
    <Using Include="TUnit.Assertions.Should" />
    <Using Include="TUnit.Assertions.Should.Extensions" />
  </ItemGroup>
</Project>
