name: Code Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: Setup .NET
      uses: actions/setup-dotnet@v6.0.0
      with:
        dotnet-version: '8.0.x'

    - name: Test Code
      working-directory: ./v2rayN
      run: dotnet test ./ServiceLib.Tests
